// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ18X1IbUertbYyYpxFXpoTt0EvbVtif4',
    appId: '1:17348755579:web:de8057b8fa7e33f1f2a2de',
    messagingSenderId: '17348755579',
    projectId: 'jidlo-je-lek',
    authDomain: 'jidlo-je-lek.firebaseapp.com',
    storageBucket: 'jidlo-je-lek.appspot.com',
    measurementId: 'G-TEVDX0QK9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqY-OQJT4IwcJFDOqtjPBHwZ3jiTCAJSo',
    appId: '1:17348755579:android:b14ce486d66024a7f2a2de',
    messagingSenderId: '17348755579',
    projectId: 'jidlo-je-lek',
    storageBucket: 'jidlo-je-lek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrV4KGAkT9slPwMPfhhthnrCnzQ3cc8wE',
    appId: '1:17348755579:ios:ca968c87d6cc3899f2a2de',
    messagingSenderId: '17348755579',
    projectId: 'jidlo-je-lek',
    storageBucket: 'jidlo-je-lek.appspot.com',
    androidClientId: '17348755579-ncoqbcok7vketnkpppt71k19iooi3hcu.apps.googleusercontent.com',
    iosClientId: '17348755579-koa22pueta77m674eh9ljogr0esfktge.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrV4KGAkT9slPwMPfhhthnrCnzQ3cc8wE',
    appId: '1:17348755579:ios:9b0bf6cda7c12337f2a2de',
    messagingSenderId: '17348755579',
    projectId: 'jidlo-je-lek',
    storageBucket: 'jidlo-je-lek.appspot.com',
    androidClientId: '17348755579-ncoqbcok7vketnkpppt71k19iooi3hcu.apps.googleusercontent.com',
    iosClientId: '17348755579-n1nuq3qbth62als57p3j7j02ba7ogjd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.stacionarApp',
  );
}
